# @package model

meta:
  name: 'distill'

cls:
  _target_: src.model.distill.DistillContext
  optimizer:
    _partial_: true
    _target_: torch.optim.AdamW
    lr: 1e-3
    weight_decay: 1e-4

  distillsize: 100

train_call:
  n_steps: 100
  val_log_frequency: 1
  batch_size: 32