# @package model

meta:
  name: 'distill'

cls:
  _target_: src.model.distill.DistillContext
  model:
    _target_: ifbo.surrogate.FTPFN
    version: "0.0.1"
    device: ${device}
    target_path: ${repo_root}/data/.model
  optimizer:
    _partial_: true
    _target_: torch.optim.AdamW
    lr: 1e-3
    weight_decay: 1e-4

  distillsize: 100

  decay_fn:
    _partial_: True
    _target_: src.model.mixture.decay.constant_exponential
    lambda_: 0.005
    constant: 0

  mixture_fn:
    _partial_: True
    _target_: src.model.mixture.mixing.argmin

  min_context_size: 10

train_call:
  n_steps: 50
  val_log_frequency: 1
  batch_size: 32