cls:
  _target_: src.model.ifbo.IFBO_mixture
  # FIXME: check api.py _run_args for pipeline search space instantiation
#  pipeline_space
#  Out[4]: <neps.search_spaces.search_space.SearchSpace at 0x7ff91433faf0>
#  max_cost_total
#  searcher_config
#  Out[6]:
  acquisition: 'MFPI-random'
  acquisition_args: None
  acquisition_sampler: 'freeze-thaw'
  acquisition_sampler_args: None
  surrogate_model: 'pfn'
  surrogate_model_args:
    model_name: 'bopfn_broken_unisep_1000curves_10params_2M'
    checkpointing: True
    root_directory: 'neps_root_directory'
  initial_design_fraction: None
  initial_design_size: 1
  initial_design_budget: 1
  loss_value_on_error: None
  cost_value_on_error: None
  ignore_errors: False
