# @package model

meta:
  name: 'pfn_impute-cv'

cls:
  _target_: src.model.pfnimputation.PFNPriorImputation

  model:
    _target_:  ifbo.surrogate.FTPFN
    version: "0.0.1"
    device: ${device}
    target_path: ${repo_root}/data/.model

  mixture_strategy:
    _target_: src.model.mixing.CVMixtureStrategy
    _partial_: true

  criterion: Null
  min_context_size: 10
  verbose: True
  # related_task_data



