# @package model
defaults:
  - /model/decay/exp@cls.decay_fn
  - /model/mixture/acq_pi@cls.mixture_fn
  - /model/reliability/scaled@cls.reliability_fn

meta:
  name: 'pfn_impute'

cls:
  _target_: src.model.pfnimputation.PFNPriorImputation

  model:
    _target_:  ifbo.surrogate.FTPFN
    version: "0.0.1"
    device: ${device}
    target_path: ${repo_root}/data/.model

  criterion: Null
  min_context_size: 10
  verbose: false
  # related_task_data



