# @package model

meta:
  name: 'pfn_mixture'

cls:
  _target_: src.model.mixture.mixture_ppd.PFNPPDMixture

  model:
    _target_:  ifbo.surrogate.FTPFN
    version: "0.0.1"
    device: ${device}
  decay_fn:
    _partial_: True
    _target_: src.model.mixture.decay.constant_exponential
    lambda_: 0.01
    constant: 200

  mixture_fn:
    _partial_: True
    _target_:  src.model.mixture.mixing.argmin

  criterion: Null
  min_context_size: 10
  # related_task_data

inference_kwargs:
  temperature: 1.0