# @package model
defaults:
  - /model/decay/exp@cls.decay_fn
  - /model/mixture/argmin@cls.mixture_fn
  - /model/reliability/scaled@cls.reliability_fn

meta:
  name: 'pfn_argmin'

cls:
  _target_: src.model.mixture_ppd.PFNPPDMixture

  model:
    _target_:  ifbo.surrogate.FTPFN
    version: "0.0.1"
    device: ${device}
    target_path: ${repo_root}/data/.model

  criterion: Null
  min_context_size: 10
  # related_task_data

inference_kwargs:
  temperature: 1.0