# @package benchmark

meta:
  name: 'pd1'

cls:
  _target_: src.dataset.mfpbenchprior.MFBenchPrior
  name: pd1_tabular
  data_path: ${repo_root}/data/pd1-tabular
#  task_id: 0
#  related_task_ids: [1, 2, 3]

tabular: true