# @package benchmark

meta:
  name: 'sanity_related'

cls:
  _target_: src.dataset.taskprior.MetaTaskPriorResampleLayers
  n_layers: 1
  dim_hyperparameters: 3
  n_fidelities: 100
  seq_len: 1000

sample_config:

  n_tasks: 6 # incl. target task